### ISSUE TITLE
Typo error and a suggestion 

### ISSUE THREAD

**Issue by aravindajith** [surjithctly/Better-Envato#11]
Hey Surjith,
- The new "Remember to Withdraw" label has a typo error. One '_m_' is missing
- Suggestion: Change '_Remember me to withdraw_' to '_**Remind** me to_' 

Been using your extension for months. Great work. :+1: 

Regards,

Aravind Ajith

**Comment by surjithctly** [comment]
Hello Aravind,

Thanks so much. Noted. Will be live soon :)

(Let me know what other feature you would like to add)

~Surjith

**Comment by aravindajith** [comment]
Awesome!

The other feature - a better statement page. Plugin had that feature before the taxes came in, right?

**Comment by surjithctly** [comment]
yes. 

It conflicted with the new support / tax lines and its really hard to hack the front-end. Envato promised for a better statement page. let's hope they add it soon.

~Surjith

**Comment by aravindajith** [comment]
Got it. Thanks mate :) Keep up the great work.

**Comment by surjithctly** [comment]
Fixed in v2.2.0
