### ISSUE TITLE
Show earnings amount in your local currency (Header)

### ISSUE THREAD

**Issue by ghost** [surjithctly/Better-Envato#12]
Hi Surjith S M , thanks for your great extension.
The extension don't show earnings amount in my local currency in header.
all other things works fine except this
any Idea ?

**Comment by surjithctly** [comment]
Hello,

Did you obtain API key from Open Exchange rate? Then you need to put it there. 

Or is it working previously and stopped now? Can you send some screenshots? 

~Surjith

**Comment by surjithctly** [comment]
As there's no reply from the OP, Closing this now.

**Comment by abszar** [comment]
+1
