### ISSUE TITLE
Currency on imac

### ISSUE THREAD

**Issue by elusivethemes** [surjithctly/Better-Envato#13]
Hi,

ive just switched from pc to a mac, installed this and entered my currency api key etc but its still wont change the currency to GBP. Any ideas ?

Thanks,

Scott

**Comment by surjithctly** [comment]
That's strange.

Do you see any console errors? (right click => inspect element => console)

~Surjith

**Comment by elusivethemes** [comment]
Yes theres this one : 

https://api.envato.com/v1/market/private/user/account.json Failed to load resource: the server responded with a status of 403 (Forbidden)

Awsome plugin by the way.

**Comment by surjithctly** [comment]
So that means your Envato Personal Token is
1. Either Wrong or
2. You have not checked all checkboxes when creating personal token.

can you confirm that?

~Surjith

**Comment by elusivethemes** [comment]
ahh i was using the old api, its working now. Thanks for the help 👍

**Comment by surjithctly** [comment]
Ahh... Glad to hear that!
