### ISSUE TITLE
Show earnings amount in your local currency (Header)

### ISSUE THREAD

**Issue by abszar** [surjithctly/Better-Envato#16]
Hi Surjith S M , thanks for your great extension.
The extension don't show earnings amount in my local currency in header.
all other things works fine except this
any Idea ?

PS: i finded this issue closed so i recreated it (plz Help)

thank you

**Comment by abszar** [comment]
i Did you obtain the API key from Open Exchange rate
+ it work with : 
- Show earnings page in your local currency
- Show earnings in statements in your local currency

but not with the header one

in my old computer it was working fine - i don't know what happened now

**Comment by surjithctly** [comment]
Hello,

Thanks for reporting. Do you see any errors in the Console? (Chrome -> Devtools -> Console)

Please send me the screenshots.

**Comment by abszar** [comment]
thank you for responding 
attached the screenshot
![capture](https://cloud.githubusercontent.com/assets/5203446/21498195/c1d022b2-cc2a-11e6-8d1c-b58376af5e3b.PNG)

**Comment by surjithctly** [comment]
Hmm.. The error says, token expired or not valid. Can you please add new Personal Token in the Better Envato Options page?

**Comment by abszar** [comment]
OH yeah, it work now :)

thank you very much
